namespace Milabowl.Processing.DataImport.Models;

public record PlayerEvent(
    string FirstName,
    string Surname,
    //Guid PlayerEventId,
    int FantasyPlayerEventId,
    // Player Player,
    //Guid FkPlayerId,
    //Event Event,
    //Guid FkEventId,
    int Minutes,
    int GoalsScored,
    int Assists,
    int GoalsConceded,
    int CleanSheets,
    int PenaltiesSaved,
    int OwnGoals,
    int PenaltiesMissed,
    int YellowCards,
    int RedCards,
    int Saves,
    int Bonus,
    int Bps,
    string Influence,
    string Creativity,
    string Threat,
    string IctIndex,
    int TotalPoints,
    bool InDreamteam,
    int Multiplier,
    bool IsCaptain,
    bool IsViceCaptain,
    int PlayerPosition
);
