name: Run .NET Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build with warnings as errors
        run: dotnet build milabowl-backend/Milabowl.sln --configuration Release --warnaserror

      - name: Run tests
        id: tests
        run: dotnet test milabowl-backend/Milabowl.Processing.Tests/Milabowl.Processing.Tests.csproj --no-build --configuration Release --verbosity normal --logger:"junit;LogFileName={assembly}.results.xml" --results-directory "TestResults"

      - name: Generate test summary
        shell: pwsh
        run: ./milabowl-backend/scripts/generate-test-summary.ps1 "TestResults" >> $env:GITHUB_STEP_SUMMARY
        if: steps.tests.outcome == 'success'

  code-quality-backend:
    runs-on: ubuntu-latest
    name: Backend Code Quality Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Install dotnet tools
        working-directory: ./milabowl-backend
        run: dotnet tool restore

      - name: Check formatting
        working-directory: ./milabowl-backend
        run: dotnet csharpier check . --config-path .editorconfig

  code-quality-frontend:
    runs-on: ubuntu-latest
    name: Frontend Code Quality Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: milabowl-astro/package-lock.json

      - name: Install dependencies
        working-directory: ./milabowl-astro
        run: npm ci

      - name: Check formatting with Prettier
        working-directory: ./milabowl-astro
        run: npx prettier --check .

      - name: Check code quality with ESLint
        working-directory: ./milabowl-astro
        run: npx eslint .
