name: Run .NET Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build with warnings as errors
        run: dotnet build milabowl-backend/Milabowl.sln --configuration Release --warnaserror

      - name: Run tests
        id: tests
        run: dotnet test milabowl-backend/Milabowl.Processing.Tests/Milabowl.Processing.Tests.csproj --no-build --configuration Release --verbosity normal --logger:"junit;LogFileName={assembly}.results.xml" --results-directory "TestResults"

      - name: Generate test summary
        shell: pwsh
        run: ./milabowl-backend/scripts/generate-test-summary.ps1 "TestResults" >> $env:GITHUB_STEP_SUMMARY
        if: steps.tests.outcome == 'success'

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Install dotnet tools
        working-directory: ./milabowl-backend
        run: dotnet tool restore

      - name: Check formatting
        working-directory: ./milabowl-backend
        run: dotnet csharpier check . --config-path .editorconfig
